
services:
  sambafs:
    image: rardcode/sambafs
    container_name: sambafs
    restart: unless-stopped
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
    #environment:
    #  - USER1=user|pass
    volumes:
    #- /srv/samba:/srv/samba
    - ./data:/data
    #command: '-u user1:user1pwd'
